server:
  port: 9096
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/food_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        ddl-auto: update
      show-sql: true




#    eureka configurations
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost #LAPTOP-A5QB0QAD
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"



info:
  app:
    name: "Food Service"
    description: "This is Food Service. Ready to serve users."
    version: "1.0 Production"